### ISSUE TITLE
A little Problem many novice users will face...

### ISSUE THREAD

**Issue by Nikostito** [ahmadhashemi/Immortal#1]
Hey man. Just a heads up for the shitstorm of comments you might get from first time jailbreakers.
Your tweak although it's amazing will not work wel in accordance with yalu. And that's why everyone will use their Apple id that used to sign Yalu in order to sign every other app. So if they install 3 apps or more with the same id, their yalu app will become revoked without them knowing (I assume they do not knw that they can sign 3 apps every week). So the next time they reboot or run out of battery and aren't near a pc, they'll get stuck on no-jb mode without them understanding why their app doesn't open... Hope i explained it as good as I could

**Comment by racerx8967** [comment]
What if you were to redo Yalu after removing it? Method used to upgrade Yalu. Seems like that could probably work. Dev please comment.

**Comment by Nikostito** [comment]
Yeah it will, but you always need to sign Yalu last, or use a second Apple id

**Comment by asadhLION** [comment]
@Ntdark13 So if I understand your comment, even tho the Immortal tweak allows us to exceed the 3 Apps limit, (example :) the first installed app after the 4th installed with CydiaImpactor will not work anymore because of the 3 apps limit? Which means that if we want to use this Immortal tweak correctly, we'll have to have a different Apple ID each time we installed our 3rd app with the same? Right?

**Comment by SaeedHaidar** [comment]
I put Yalu.app from Filza to application folder now reboot my phone and I also crashed it one myself i can re jailbreak again (I not use this tweak)

**Comment by SaeedHaidar** [comment]
I delete the other one with I installed with cydia impactor now it's work for every I also can change it if another Yalu update comes

**Comment by racerx8967** [comment]
Hashsum mismatch can't install. 10.2 6s+ also maybe I'm not understanding correctly....
Immortal says:
Install unlimited amount of apps on same profile never expire or removed.

Yet Yalu will disappear after the 4th? That doesn't make much sense and defeats the purpose of this tweak does it?

**Comment by Nikostito** [comment]
@asadhLION No, it means that the 4th app you'll install will create a new provisioning profile, revoking the previous one with which you sideloaded the 3 first apps of yours. You don't need multiple ids. You have to remember eithe rto sign yalu last in order for it to get signed with a new provisioning profile, or sign yalu with a second id different from the id you use to sign every other app.
As long as you sign Yalu last, all your other apps even if you sideload 100, will work in Jb mode,

**Comment by Nikostito** [comment]
@racerx8967 Yeah, that's why is best to use a second apple id

**Comment by racerx8967** [comment]
Oh ok gotcha, it just keeps installing profiles.. rather then having them all on one?

**Comment by Nikostito** [comment]
Yeah cause every free profile lets 3 apps to be sideloaded

**Comment by racerx8967** [comment]
Alrighty. Also hashsum mismatch now fixed. Thank you if anyone did anything. Lol.

**Comment by ahmadhashemi** [comment]
I think we have some invalid information here. To make it clear, free Apple IDs have two limitations for side-loading:

1. You can have 3 side-loaded application on one device **simultaneously**.
2. You can side-load maximum number of **10 applications each week**.

Immortal tweak removes first limit, because it's something which is check on device. You just need to restart your device after installing each 3 applications and continue installing 3 other; until you reach 10 applications per 7 days limit.

Second limit is set on Apple's server and can't get bypassed using any tweak. **So here is how you can use tweak:**

- You can add 10 new applications each week with same account used before, without getting previous applications expired. Nothing gets expired or revoked, but you have limit of 10 application per week.
- You can use multiple accounts, and resign 10 applications in week using each one. So you can resign as many as applications and games you want, by changing account when you reach 10 resigns per week.

I will add this answer to ReadMe file to make things clear for other users.

**Comment by asadhLION** [comment]
@ahmadhashemi Oh wow, that's very clear explanation, thanks brother!

**Comment by Nikostito** [comment]
@ahmadhashemi Ohhh, so after 10. Ok got it. Didn't know that thanks for clearance

**Comment by racerx8967** [comment]
Ok I figured that's how it worked. Thank you Dev for clarifying that. I kept saying to myself "if hat were the case the tweak would be useless". Very good job! Any link for donations?

**Comment by ahmadhashemi** [comment]
Thanks for you kindness. Maybe in future, but for now there is no link for donations. I do this stuff just for fun and love. Enjoy and spread! that's all this stuff is developed for.
